from django.utils.translation import gettext_lazy, ngettext_lazy, pgettext_lazy, npgettext_lazy  # noqa


def __messages__():
    gettext_lazy(message="""Activity""")
    gettext_lazy(message="""Collaboration Type""")
    gettext_lazy(message="""Project""")
    gettext_lazy(message="""Sector""")
    gettext_lazy(message="""{ tab[1].label }""")
    ngettext_lazy(singular="""I caught %s pocket monster!. Remaining: %s""", plural="""?""", number="""1""")
    ngettext_lazy(singular="""There is %(total)s object. Remaining: %(count)s""", plural="""?""", number="""1""")
    ngettext_lazy(singular="""There is one activity""", plural="""There are many activities""", number="""1""")
    npgettext_lazy(context="""bar""", singular="""There is one activity""", plural="""There are many activities""", number="""1""")
    npgettext_lazy(context="""foo""", singular="""There is one activity""", plural="""There are many activities""", number="""1""")
    pgettext_lazy(context="""animal""", message="""Elephant""")
    pgettext_lazy(context="""editor""", message="""%(project_or_activity)s Description""")
    pgettext_lazy(context="""editor""", message="""%(project_or_activity)s Objectives""")
    pgettext_lazy(context="""editor""", message="""%(project_or_activity)s Status""")
    pgettext_lazy(context="""editor""", message="""%(project_or_activity)s Target Groups""")
    pgettext_lazy(context="""editor""", message="""%(project_or_activity)s Title""")
    pgettext_lazy(context="""editor""", message="""%s Partner ID""")
    pgettext_lazy(context="""editor""", message="""A detailed description of the %(project_or_activity)s objectives and its expected outcomes.""")
    pgettext_lazy(context="""editor""", message="""Details of groups that are intended to benefit from the %(project_or_activity)s.""")
    pgettext_lazy(context="""editor""", message="""Expected Finish Date""")
    pgettext_lazy(context="""editor""", message="""Expected Start Date""")
    pgettext_lazy(context="""editor""", message="""Save and Next""")
    pgettext_lazy(context="""editor""", message="""Save""")
    pgettext_lazy(context="""editor""", message="""This explains what the %(project_or_activity)s is, it’s longer than the title and contains more detail.""")
    pgettext_lazy(context="""month""", message="""Elephant""")
    pgettext_lazy(context="""month""", message="""may""")
    pgettext_lazy(context="""verb""", message="""may""")
