# Generated by Django 3.1.7 on 2021-04-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.CharField(help_text='The message text to translate from', max_length=512, unique=True)),
                ('msgid_plural', models.CharField(blank=True, help_text='Optional plural form of the message', max_length=512, null=True)),
                ('comment_for_translators', models.CharField(blank=True, max_length=2000, null=True)),
                ('context', models.CharField(blank=True, help_text='Optional context marker for the message', max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgstr', models.CharField(max_length=512)),
                ('msgstr_plurality', models.IntegerField(blank=True, help_text='Which plural form this translation refers to', null=True)),
                ('language', models.CharField(max_length=5)),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettext_utils.translationsource')),
            ],
        ),
        migrations.CreateModel(
            name='CommonText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('translated_string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettext_utils.translationsource', to_field='msgid')),
            ],
        ),
    ]
